# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/assets/loginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginScreen(object):
    def setupUi(self, loginScreen):
        loginScreen.setObjectName("loginScreen")
        loginScreen.resize(1280, 720)
        loginScreen.setWindowOpacity(1.0)
        self.inputUserName = QtWidgets.QLineEdit(loginScreen)
        self.inputUserName.setGeometry(QtCore.QRect(490, 220, 300, 60))
        self.inputUserName.setObjectName("inputUserName")
        self.inputPassword = QtWidgets.QLineEdit(loginScreen)
        self.inputPassword.setGeometry(QtCore.QRect(490, 330, 300, 60))
        self.inputPassword.setObjectName("inputPassword")
        self.btnLogin = QtWidgets.QPushButton(loginScreen)
        self.btnLogin.setGeometry(QtCore.QRect(440, 440, 160, 40))
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(loginScreen)
        self.btnRegister.setGeometry(QtCore.QRect(660, 440, 160, 40))
        self.btnRegister.setObjectName("btnRegister")

        self.retranslateUi(loginScreen)
        QtCore.QMetaObject.connectSlotsByName(loginScreen)

    def retranslateUi(self, loginScreen):
        _translate = QtCore.QCoreApplication.translate
        loginScreen.setWindowTitle(_translate("loginScreen", "LoginScreen"))
        self.btnLogin.setText(_translate("loginScreen", "Login"))
        self.btnRegister.setText(_translate("loginScreen", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginScreen = QtWidgets.QWidget()
    ui = Ui_loginScreen()
    ui.setupUi(loginScreen)
    loginScreen.show()
    sys.exit(app.exec_())
