# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/assets/menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(128, 0, 207, 255), stop:0.55 rgba(128, 0, 235, 255), stop:0.98 rgba(234, 0, 119, 255), stop:1 rgba(0, 0, 0, 0));")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(70, 240, 651, 161))
        self.textEdit.setStyleSheet("background: transparent;\n"
"border:none;")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(870, 30, 330, 90))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"   background-color: rgb(85, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: all 0.3s ease;\n"
"    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\n"
"    text-transform: uppercase;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(255, 0, 110);\n"
"    transform: scale(1.05);\n"
"    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: scale(0.95);\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(800, 170, 330, 90))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"   background-color: rgb(85, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: all 0.3s ease;\n"
"    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\n"
"    text-transform: uppercase;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(255, 0, 110);\n"
"    transform: scale(1.05);\n"
"    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: scale(0.95);\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(870, 310, 330, 90))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   background-color: rgb(85, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: all 0.3s ease;\n"
"    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\n"
"    text-transform: uppercase;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(255, 0, 110);\n"
"    transform: scale(1.05);\n"
"    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: scale(0.95);\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(800, 450, 330, 90))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"   background-color: rgb(85, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: all 0.3s ease;\n"
"    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\n"
"    text-transform: uppercase;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(255, 0, 110);\n"
"    transform: scale(1.05);\n"
"    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: scale(0.95);\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 40, 291, 111))
        self.textEdit_2.setStyleSheet("background: transparent;\n"
"border:none;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(870, 590, 330, 90))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background-color: rgb(85, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    transition: all 0.3s ease;\n"
"    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\n"
"    text-transform: uppercase;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: rgb(255, 0, 110);\n"
"    transform: scale(1.05);\n"
"    box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    transform: scale(0.95);\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>Welcome to Dolliet\'s Bank</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:20px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,sans-serif\'; font-size:32pt; font-weight:600; color:#ffffff;\">Welcome to Dolliet\'s Mint-Looking Bank 💰</span><span style=\" font-family:\'Arial,sans-serif\'; font-size:8pt; color:#ffffff;\"> </span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "I am Customer"))
        self.pushButton_2.setText(_translate("Form", "I Want to Become a Customer"))
        self.pushButton_3.setText(_translate("Form", "Search Current Currency Rates"))
        self.pushButton_4.setText(_translate("Form", "Customer List (Admin Only)"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">IV/II/MMXXV</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">20:59</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Form", "Play Coin Guess Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
